CREATE TABLE [dbo].[Company]
(
    [Id]           INT              IDENTITY (1, 1) NOT NULL,
    [Name]         NVARCHAR (200)   NOT NULL,
    [LegalName]    NVARCHAR (200)   NULL,
    [Gstin]        NVARCHAR (20)    NOT NULL,
    [Pan]          NVARCHAR (20)    NOT NULL,
    [Cin]          NVARCHAR (30)    NULL,
    [IndustryId]   INT              NULL,
    [Address]      NVARCHAR (500)   NOT NULL,
    [City]         NVARCHAR (200)   NOT NULL,
    [StateId]      INT              NULL,
    [PinCode]      INT              NULL,
    [PhoneNo]      NVARCHAR (15)    NOT NULL,
    [Mobile]       BIGINT           NULL,
    [Website]      NVARCHAR (200)   NULL,
    [Email]        NVARCHAR (200)   NULL,
    [LogoPath]     NVARCHAR (400)   NULL,
    [CreatedBy]    NVARCHAR (100)   NULL,
    [CreatedDate]  DATETIME2 (7)    NOT NULL CONSTRAINT [DF_Company_CreatedDate] DEFAULT (SYSUTCDATETIME()),
    [ModifiedBy]   NVARCHAR (100)   NULL,
    [ModifiedDate] DATETIME2 (7)    NULL,
    [UpdateTag]    NVARCHAR (50)    NULL,
    [UpdateGuid]   UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Company_UpdateGuid] DEFAULT (NEWID()),
    [IsDeleted]    BIT              NOT NULL CONSTRAINT [DF_Company_IsDeleted] DEFAULT (0),
    CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Company_Industries] FOREIGN KEY ([IndustryId]) REFERENCES [dbo].[Industries] ([Id]),
    CONSTRAINT [FK_Company_State] FOREIGN KEY ([StateId]) REFERENCES [dbo].[State] ([Id])
);
